steps:
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 'pull', 'gcr.io/kolide-public-containers/xar:latest' ]
      id: 'pull-xar-image'
    - name: 'gcr.io/cloud-builders/docker'
      args: [ 
                'build', 
                '--cache-from', 'gcr.io/kolide-public-containers/xar:latest',
                '-t', 'gcr.io/kolide-public-containers/xar', 
                '.' 
            ]
      waitFor: ['pull-xar-image']
      id: 'build-xar-image'
    - name: 'gcr.io/kolide-public-containers/xar:latest'
      args: ['xar', '--help']
      waitFor: ['build-xar-image']
images:
    - 'gcr.io/kolide-public-containers/xar'
